In [ ]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]])
X_scaled = preprocessing.scale(X_train)
X_scaled

In [5]:
X_scaled.mean(axis=0) #axis=0是输出矩阵按行，axis=1是输出矩阵按列

array([ 0.,  0.,  0.])

In [8]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.])

In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
scaler.mean_

array([ 1.        ,  0.        ,  0.33333333])

In [13]:
scaler.scale_

array([ 0.81649658,  0.81649658,  1.24721913])

In [14]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [23]:
min_max_scaler = preprocessing.MinMaxScaler() #缩放到给定范围：[0,1]
X_train_minmax = min_max_scaler.fit(X_train)
X_train_minmax.transform(X_train)

array([[ 0.5       ,  0.        ,  1.        ],
       [ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  1.        ,  0.        ]])

In [38]:
X_train_minmax.scale_

array([ 0.5       ,  0.5       ,  0.33333333])

In [31]:
X_test_1 = np.array([[-3.,-1.,4.]])
X_test_1_minmax = min_max_scaler.transform(X_test_1)
X_test_1_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

In [33]:
min_max_scaler_range_given = preprocessing.MinMaxScaler(feature_range=(0,2)) #缩放到给定范围：[0,1]
X_train_minmax_range_given = min_max_scaler_range_given.fit(X_train)
X_train_minmax_range_given.transform(X_train)

array([[ 1.        ,  0.        ,  2.        ],
       [ 2.        ,  1.        ,  0.66666667],
       [ 0.        ,  2.        ,  0.        ]])

In [39]:
X_train_minmax_range_given.scale_

array([ 1.        ,  1.        ,  0.66666667])