In [7]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]])
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [5]:
X_scaled.mean(axis=0) #axis=0是输出矩阵按行，axis=1是输出矩阵按列

array([ 0.,  0.,  0.])

In [8]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.])

In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
scaler.mean_

array([ 1.        ,  0.        ,  0.33333333])

In [13]:
scaler.scale_

array([ 0.81649658,  0.81649658,  1.24721913])

In [14]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [23]:
min_max_scaler = preprocessing.MinMaxScaler() #缩放到给定范围：[0,1]
X_train_minmax = min_max_scaler.fit(X_train)
X_train_minmax.transform(X_train)

array([[ 0.5       ,  0.        ,  1.        ],
       [ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  1.        ,  0.        ]])

In [38]:
X_train_minmax.scale_

array([ 0.5       ,  0.5       ,  0.33333333])

In [31]:
X_test_1 = np.array([[-3.,-1.,4.]])
X_test_1_minmax = min_max_scaler.transform(X_test_1)
X_test_1_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

In [33]:
min_max_scaler_range_given = preprocessing.MinMaxScaler(feature_range=(0,2)) #缩放到给定范围：[0,1]
X_train_minmax_range_given = min_max_scaler_range_given.fit(X_train)
X_train_minmax_range_given.transform(X_train)

array([[ 1.        ,  0.        ,  2.        ],
       [ 2.        ,  1.        ,  0.66666667],
       [ 0.        ,  2.        ,  0.        ]])

In [39]:
X_train_minmax_range_given.scale_

array([ 1.        ,  1.        ,  0.66666667])

In [10]:
#分位数
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
X,y = iris.data,iris.target
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)
X_train


array([[ 5.9,  3. ,  4.2,  1.5],
       [ 5.8,  2.6,  4. ,  1.2],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 6.9,  3.1,  5.1,  2.3],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 5. ,  2. ,  3.5,  1. ],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6. ,  2.2,  5. ,  1.5],
       [ 6.7,  2.5,  5.8,  1.8],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 6.3,  3.3,  4.7,  1.6],
       [ 5.5,  2.4,  3.8,  1.1],
       [ 6.3,  2.7,  4.9,  1.8],
       [ 6.3,  2.8,  5.1,  1.5],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 6.3,  2.5,  5. ,  1.9],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 6.5,  3. ,  5.2,  2. ],
       [ 6. ,  3.4,  4.5,  1.6],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 5.6,  2.9,  3.6,  1.3],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 6.1,  3. ,  4.6,  1.4],
       [ 7.2,  3.2,  6. ,  1.8],
       [ 5

In [12]:
quantile_transformer = preprocessing.QuantileTransformer(random_state=0)
X_train_trans = quantile_transformer.fit_transform(X_train)
X_train_trans

array([[  5.49549550e-01,   4.36936937e-01,   4.81981982e-01,
          5.90090090e-01],
       [  5.09009009e-01,   1.62162162e-01,   4.23423423e-01,
          4.14414414e-01],
       [  8.51351351e-01,   4.36936937e-01,   8.06306306e-01,
          8.51351351e-01],
       [  6.75675676e-02,   6.70670671e-01,   4.50450450e-02,
          1.39639640e-01],
       [  8.78378378e-01,   5.76576577e-01,   7.16216216e-01,
          9.32432432e-01],
       [  1.75675676e-01,   8.69369369e-01,   2.75275275e-01,
          3.24324324e-01],
       [  3.19819820e-01,   9.18418418e-01,   1.98198198e-01,
          1.39639640e-01],
       [  1.75675676e-01,   9.99999998e-08,   3.55355355e-01,
          3.51851852e-01],
       [  7.43243243e-01,   4.36936937e-01,   8.06306306e-01,
          6.98698699e-01],
       [  8.02802803e-01,   7.47747748e-01,   8.64864865e-01,
          9.99999900e-01],
       [  5.76576577e-01,   1.35135135e-02,   6.71171171e-01,
          5.90090090e-01],
       [  8.10310310e

In [13]:
X = [[1.,-1.,2.],[2.,0.,0.,],[0.,1.,-1.]]
binarizer = preprocessing.Binarizer().fit(X)
binarizer.transform(X)

array([[ 1.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [15]:
binarizer = preprocessing.Binarizer(threshold=2)
binarizer.transform(X)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])